// Generated by CoffeeScript 1.12.1
(function() {
  var CacheImage, FilterPiexif, imageList, myMap, speaker;

  myMap = spexif.myMap;

  speaker = spexif.speaker;

  imageList = spexif.imageList;

  CacheImage = (function() {
    function CacheImage(dataURL) {
      if (dataURL.slice(0, 22) !== 'data:image/jpeg;base64') {
        throw speaker.errorFreindly('input is not jpeg file!');
      }
      this.dataURL = dataURL;
      this.createEXIF();
      this.createImageNode();
      this.createHTMLNode();
      if (this.exif.gps) {
        this.createPoint();
      }
      imageList.add(this);
    }

    CacheImage.prototype.createPoint = function() {
      return this.mapPoint = myMap.createPoint(this);
    };

    CacheImage.prototype.createImageNode = function() {
      var imageNode;
      imageNode = document.createElement('img');
      imageNode.src = this.dataURL;
      return this.imageNode = imageNode;
    };

    CacheImage.prototype.createHTMLNode = function() {
      var HTMLNode;
      HTMLNode = document.createElement('div');
      HTMLNode.className = 'image-info';
      HTMLNode.appendChild(this.imageNode);
      HTMLNode.appendChild(this.exif.HTMLNode);
      return this.HTMLNode = HTMLNode;
    };

    CacheImage.prototype.createEXIF = function() {
      var halfExif;
      halfExif = piexif.load(this.dataURL);
      return this.exif = new FilterPiexif(halfExif);
    };

    return CacheImage;

  })();

  FilterPiexif = (function() {
    function FilterPiexif(exif) {
      var err;
      try {
        this.date = this.getDate(exif.Exif);
      } catch (error) {
        err = error;
        speaker.error(err);
        speaker.errorFreindly("can't get date of photo. ");
      }
      try {
        this.maker = this.getMaker(exif['0th']);
      } catch (error) {
        err = error;
        speaker.error(err);
        speaker.errorFreindly("can't get camera of photo. ");
      }
      try {
        this.gps = [this.getGPS(exif.GPS, "GPSLongitude"), this.getGPS(exif.GPS, "GPSLatitude")];
      } catch (error) {
        err = error;
        speaker.error(err);
        speaker.errorFreindly("can't get gps data of photo. ");
      }
      this.createHTMLNode();
    }

    FilterPiexif.prototype.getMaker = function(exif) {
      return exif[piexif.ImageIFD.Make].trim();
    };

    FilterPiexif.prototype.getDate = function(exif) {
      var date;
      date = exif[piexif.ExifIFD.DateTimeOriginal].split(' ');
      date[0] = date[0].replace(/:/g, '-');
      return date.join('T');
    };

    FilterPiexif.prototype.getGPS = function(exif, key) {
      var decimal, dms, i, len, part, ratio;
      dms = exif[piexif.GPSIFD[key]];
      ratio = 1;
      decimal = 0;
      for (i = 0, len = dms.length; i < len; i++) {
        part = dms[i];
        decimal += part[0] / part[1] / ratio;
        ratio *= 60;
      }
      return decimal;
    };

    FilterPiexif.prototype.createHTMLNode = function() {
      var HTMLNode;
      HTMLNode = document.createElement('pre');
      HTMLNode.textContent = [this.date, this.maker, this.gps].join('\n');
      return this.HTMLNode = HTMLNode;
    };

    return FilterPiexif;

  })();

  spexif.CacheImage = CacheImage;

}).call(this);
