// Generated by CoffeeScript 1.12.1
(function() {
  var Speaker;

  Speaker = (function() {
    function Speaker(shower) {
      this.debuger = shower.debuger;
      this.boardNode = shower.boardNode;
    }

    Speaker.prototype.errorFreindly = function(err) {
      this.boardNode.textContent += err + '\r\n';
      this.debuger.error(err);
      return err;
    };

    Speaker.prototype.error = function(err) {
      return this.debuger.error(err);
    };

    Speaker.prototype.log = function(lg) {
      return this.debuger.log(lg);
    };

    return Speaker;

  })();

  spexif.speaker = new Speaker({
    debuger: window.console,
    boardNode: document.getElementById('error-board')
  });

}).call(this);
