// Generated by CoffeeScript 1.12.1
(function() {
  var FilterPiexif, speaker;

  speaker = spexif.speaker;

  FilterPiexif = (function() {
    var createHTMLNode, getDate, getGPS, getMaker;

    getMaker = function(exif) {
      return exif[piexif.ImageIFD.Make].trim();
    };

    getDate = function(exif) {
      return exif[piexif.ExifIFD.DateTimeOriginal];
    };

    getGPS = function(exif, key) {
      var decimal, dms, i, len, part, ratio;
      dms = exif[piexif.GPSIFD[key]];
      ratio = 1;
      decimal = 0;
      for (i = 0, len = dms.length; i < len; i++) {
        part = dms[i];
        decimal += part[0] / part[1] / ratio;
        ratio *= 60;
      }
      return decimal;
    };

    function FilterPiexif(allExif) {
      var err;
      try {
        this.date = getDate(allExif.Exif);
      } catch (error) {
        err = error;
        speaker.error(err);
        speaker.errorFreindly("can't get date of photo. ");
      }
      try {
        this.maker = getMaker(allExif['0th']);
      } catch (error) {
        err = error;
        speaker.error(err);
        speaker.errorFreindly("can't get camera of photo. ");
      }
      try {
        this.gps = [getGPS(allExif.GPS, "GPSLongitude"), getGPS(allExif.GPS, "GPSLatitude")];
      } catch (error) {
        err = error;
        speaker.error(err);
        speaker.errorFreindly("can't get gps data of photo. ");
      }
      try {
        if (!(this.thumbnail = allExif.thumbnail)) {
          throw allExif.thumbnail;
        }
      } catch (error) {
        err = error;
        speaker.error(err);
        speaker.errorFreindly("can't get thumbnail of photo. ");
      }
    }

    createHTMLNode = function() {
      var preNode;
      preNode = document.createElement('pre');
      preNode.textContent = [this.date, this.maker, this.gps].join('\n');
      return preNode;
    };

    FilterPiexif.prototype.toHTMLNode = function() {
      return this.HTMLNode || (this.HTMLNode = createHTMLNode.call(this));
    };

    return FilterPiexif;

  })();

  spexif.FilterPiexif = FilterPiexif;

}).call(this);
