// Generated by CoffeeScript 1.12.1
(function() {
  var CacheImage, ImageList, myMap,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  myMap = spexif.myMap;

  CacheImage = spexif.CacheImage;

  ImageList = (function(superClass) {
    var arrayBufferToBinaryString;

    extend(ImageList, superClass);

    function ImageList() {
      this.map = myMap;
      this.asideNode = document.getElementById('image-container');
    }

    arrayBufferToBinaryString = function(arraybuffer) {
      var charCode, charCodeToChar, u8;
      u8 = new Uint8Array(arraybuffer);
      charCodeToChar = String.fromCharCode;
      return ((function() {
        var i, len, results;
        results = [];
        for (i = 0, len = u8.length; i < len; i++) {
          charCode = u8[i];
          results.push(charCodeToChar(charCode));
        }
        return results;
      })()).join('');
    };

    ImageList.prototype.addFromBlob = function(blob) {
      var reader, url, whenArrayBufferRead;
      url = URL.createObjectURL(blob);
      reader = new FileReader();
      whenArrayBufferRead = (function(_this) {
        return function() {
          var image;
          image = new CacheImage(url, arrayBufferToBinaryString(reader.result));
          _this.push(image);
          if (image.exif.gps) {
            return _this.show(image);
          } else {
            return _this.showAside(image);
          }
        };
      })(this);
      reader.onload = whenArrayBufferRead;
      return reader.readAsArrayBuffer(blob);
    };

    ImageList.prototype.show = function(image) {
      return this.map.showPoint(image);
    };

    ImageList.prototype.showAside = function(image) {
      return this.asideNode.appendChild(image.toHTMLNode());
    };

    ImageList.prototype.addFromURL = function(url) {
      var request;
      request = new XMLHttpRequest();
      request.open('GET', url, true);
      request.responseType = 'blob';
      request.onreadystatechange = (function(_this) {
        return function() {
          var req;
          req = request;
          if (req.readyState === 4 && req.status === 200) {
            return _this.addFromBlob(req.response);
          }
        };
      })(this);
      return request.send('');
    };

    return ImageList;

  })(Array);

  spexif.imageList = new ImageList();

}).call(this);
