// Generated by CoffeeScript 1.12.1
(function() {
  var CacheImage, imageList, whenInputFiles;

  CacheImage = spexif.CacheImage;

  imageList = spexif.imageList;

  whenInputFiles = function(evt) {
    var file, i, len, results;
    window.files = evt.target.files;
    results = [];
    for (i = 0, len = files.length; i < len; i++) {
      file = files[i];
      results.push(imageList.addFromBlob(file));
    }
    return results;
  };

  (document.getElementsByTagName('input'))[0].addEventListener('change', whenInputFiles, true);

}).call(this);
