// Generated by CoffeeScript 1.12.1
(function() {
  var webFile, whenInputFiles;

  webFile = {
    read: function(file, callback) {
      var reader;
      reader = new FileReader();
      reader.onload = callback;
      return reader.readAsDataURL(file);
    },
    newCacheImage: function(evt) {
      var dataURL, image;
      dataURL = evt.target.result;
      return image = new CacheImage(dataURL);
    }
  };

  whenInputFiles = function(evt) {
    var file, files, i, len, results;
    files = evt.target.files;
    results = [];
    for (i = 0, len = files.length; i < len; i++) {
      file = files[i];
      results.push(webFile.read(file, webFile.newCacheImage));
    }
    return results;
  };

  (document.getElementsByTagName('input'))[0].addEventListener('change', whenInputFiles, true);

}).call(this);
