// Generated by CoffeeScript 1.12.1
(function() {
  var CacheImage, whenInputFiles;

  CacheImage = (function() {
    function CacheImage(file) {
      var reader;
      reader = new FileReader();
      reader.onload = this.fromDataURL.bind(this);
      reader.readAsDataURL(file);
    }

    CacheImage.prototype.fromDataURL = function(somewhat) {
      var dataURL, imageTag;
      if (typeof somewhat !== 'string') {
        dataURL = somewhat.target.result;
      } else {
        dataURL = somewhat;
      }
      console.dataURL;
      imageTag = document.createElement('img');
      imageTag.src = dataURL;
      document.body.appendChild(imageTag);
      return this.html = imageTag;
    };

    return CacheImage;

  })();

  whenInputFiles = function(evt) {
    var file, files, i, len, results;
    files = evt.target.files;
    results = [];
    for (i = 0, len = files.length; i < len; i++) {
      file = files[i];
      results.push(new CacheImage(file));
    }
    return results;
  };

  (document.getElementsByTagName('input'))[0].addEventListener('change', whenInputFiles, true);

}).call(this);
