// Generated by CoffeeScript 1.12.1
(function() {
  var Speaker;

  Speaker = (function() {
    function Speaker(shower) {
      this.debuger = shower.debuger;
      this.boardNode = shower.boardNode;
    }

    Speaker.prototype.errorTemplate = document.getElementById('template').getElementsByClassName('error-log')[0];

    Speaker.prototype.logTemplate = document.getElementById('template').getElementsByClassName('normal-log')[0];

    Speaker.prototype.errorFriendly = function(err) {
      var node;
      node = this.errorTemplate.cloneNode();
      node.textContent = err;
      this.boardNode.appendChild(node);
      this.debuger.error(err);
      return err;
    };

    Speaker.prototype.logFriendly = function(log) {
      var node;
      node = this.logTemplate.cloneNode();
      node.textContent = log;
      return this.boardNode.appendChild(node);
    };

    Speaker.prototype.error = function(err) {
      return this.debuger.error(err);
    };

    Speaker.prototype.log = function(lg) {
      return this.debuger.log(lg);
    };

    return Speaker;

  })();

  spexif.speaker = new Speaker({
    debuger: window.console,
    boardNode: document.getElementById('error-board')
  });

}).call(this);
