// Generated by CoffeeScript 1.12.1
(function() {
  var CacheImage, fileForm, imageManager, speaker, whenInputFiles;

  CacheImage = spexif.CacheImage;

  imageManager = spexif.imageManager;

  speaker = spexif.speaker;

  whenInputFiles = function(evt) {
    var file, files, i, len, results;
    files = evt.target.files;
    results = [];
    for (i = 0, len = files.length; i < len; i++) {
      file = files[i];
      results.push(imageManager.addFromBlob(file));
    }
    return results;
  };

  fileForm = document.getElementById('load-image');

  fileForm.elements[0].addEventListener('change', whenInputFiles, true);

  fileForm.addEventListener('submit', function(evt) {
    var entryName, formData, imageList, xmlRequest;
    evt.preventDefault();
    entryName = this.elements[0].name;
    imageList = spexif.imageManager.getSelectedImages();
    if (imageList.length > 0) {
      formData = new FormData();
      imageList.forEach(function(image) {
        return formData.append(entryName, image.fullImage.blob);
      });
      xmlRequest = new XMLHttpRequest();
      xmlRequest.open(this.method.toUpperCase(), this.action);
      xmlRequest.onload = function() {
        return speaker.logFriendly('successful upload selected image!');
      };
      return xmlRequest.send(formData);
    } else {
      return speaker.errorFriendly('no image selected.');
    }
  });

}).call(this);
