// Generated by CoffeeScript 1.12.1
(function() {
  var CacheImage, fileForm, imageManager, whenInputFiles;

  CacheImage = spexif.CacheImage;

  imageManager = spexif.imageManager;

  whenInputFiles = function(evt) {
    var file, files, i, len, results;
    files = evt.target.files;
    results = [];
    for (i = 0, len = files.length; i < len; i++) {
      file = files[i];
      results.push(imageManager.addFromBlob(file));
    }
    return results;
  };

  fileForm = document.getElementById('load-image');

  fileForm.elements[0].addEventListener('change', whenInputFiles, true);

  fileForm.addEventListener('submit', function(evt) {
    var entryName, formData, xmlRequest;
    evt.preventDefault();
    formData = new FormData();
    entryName = this.elements[0].name;
    spexif.imageManager.getSelectedImages().forEach(function(image) {
      return formData.append(entryName, image.fullImage.blob);
    });
    xmlRequest = new XMLHttpRequest();
    xmlRequest.open(this.method.toUpperCase(), this.action);
    return xmlRequest.send(formData);
  });

}).call(this);
