// Generated by CoffeeScript 1.12.1
(function() {
  var CacheImage, fileForm, imageManager, whenInputFiles;

  CacheImage = spexif.CacheImage;

  imageManager = spexif.imageManager;

  whenInputFiles = function(evt) {
    var file, files, i, len, results;
    files = evt.target.files;
    results = [];
    for (i = 0, len = files.length; i < len; i++) {
      file = files[i];
      results.push(imageManager.addFromBlob(file));
    }
    return results;
  };

  fileForm = document.getElementById('load-image');

  fileForm.children[0].addEventListener('change', whenInputFiles, true);

  fileForm.children[1].addEventListener('click', function(evt) {
    var formData;
    evt.preventDefault();
    formData = new FormData();
    return window.uploadImages = imageManager.getSelectedImages();
  });

}).call(this);
