// Generated by CoffeeScript 1.12.1
(function() {
  var LeafletMap, myMap;

  LeafletMap = (function() {
    var reverseLntLat;

    reverseLntLat = function(lngLat) {
      return [lngLat[1], lngLat[0]];
    };

    function LeafletMap() {
      var map, osmLayer;
      map = L.map('leaflet-map-container', {
        closePopupOnClick: false
      });
      osmLayer = new L.TileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
        attribution: "Map data © <a href=\"http://openstreetmap.org\">\nOpenStreetMap</a>\ncontributors'"
      });
      map.setView(new L.LatLng(23.652186, 120.978075), 7);
      map.addLayer(osmLayer);
      this.map = map;
    }

    LeafletMap.prototype.createPoint = function(image) {
      var marker;
      marker = L.marker(reverseLntLat(image.exif.gps));
      marker.bindPopup(image.toHTMLNode(), {
        autoClose: false
      });
      return marker;
    };

    LeafletMap.prototype.showPoint = function(image) {
      return image.mapPoint.addTo(this.map).openPopup();
    };

    LeafletMap.prototype.movePoint = function(image, lngLatArray) {
      return image.mapPoint.setLatLng(reverseLntLat(lngLatArray));
    };

    LeafletMap.prototype.removePoint = function(image) {
      if (image.mapPoint) {
        return image.mapPoint.remove();
      }
    };

    return LeafletMap;

  })();

  myMap = new LeafletMap();

  spexif.myMap = myMap;

}).call(this);
